import { useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
const Work = () => {
    const [dropDown, setDropDown] = useState(false);
    const [text, setText] = useState("America");
    const [sidebar, setSidebar] = useState(false);

    const router = useRouter();

    const dropdownHandler = () => {
        setDropDown(!dropDown);
    };

    return (
        <div>
            <Head>
                <title>Work</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className="mx-auto container px-6 lg:px-14 xl:px-0">
                <div className="hidden md:flex justify-between items-center pt-16 mb-12">
                    <div className="flex flex-row items-center space-x-10">
                        <div>
                            <a onClick={() => router.push("/landingPage")} className="cursor-pointer text-base hover:text-gray-300 focus:outline-none focus:text-gray-300 font-semibold leading-none text-white">
                                <p>Intro</p>
                            </a>
                        </div>
                        <div>
                            <a href="javascript:void(0)" className="cursor-pointer text-base hover:text-gray-300 focus:outline-none focus:text-gray-300 font-semibold leading-none text-white">
                                <p>Clients</p>
                            </a>
                        </div>
                        <div>
                            <a onClick={() => router.push("/work")} className="cursor-pointer text-base hover:text-gray-300 focus:outline-none focus:text-gray-300 font-semibold leading-none text-white">
                                <p>Work</p>
                            </a>
                        </div>
                        <div>
                            <a href="#contact" className="cursor-pointer text-base hover:text-gray-300 focus:outline-none focus:text-gray-300 font-semibold leading-none text-white">
                                <p>Contact</p>
                            </a>
                        </div>
                    </div>
                    <div className="flex justify-center items-center space-x-6">
                        <div className="flex justify-center items-center rounded-lg">
                            <button className="text-white text-2xl hover:text-gray-300 focus:outline-none focus:text-gray-300">
                                <svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M29.5493 7.54136C28.5314 7.99162 27.452 8.28732 26.3467 8.41869C27.5117 7.72194 28.3836 6.62538 28.8 5.33336C27.7067 5.98402 26.508 6.44002 25.2587 6.68669C24.4195 5.7888 23.3072 5.19331 22.0946 4.9928C20.8821 4.7923 19.6373 4.99801 18.5537 5.57796C17.4701 6.15791 16.6085 7.0796 16.1028 8.19975C15.5971 9.31989 15.4757 10.5757 15.7573 11.772C13.5402 11.6609 11.3711 11.0847 9.39106 10.0809C7.411 9.0771 5.66418 7.66809 4.26401 5.94536C3.7684 6.79662 3.50795 7.76433 3.50934 8.74936C3.50934 10.6827 4.49334 12.3907 5.98934 13.3907C5.10402 13.3628 4.23819 13.1237 3.46401 12.6934V12.7627C3.46428 14.0503 3.90983 15.2982 4.72514 16.2948C5.54044 17.2914 6.67532 17.9753 7.93734 18.2307C7.1155 18.4534 6.25375 18.4862 5.41734 18.3267C5.77317 19.435 6.46668 20.4043 7.4008 21.0988C8.33491 21.7934 9.46285 22.1784 10.6267 22.2C9.46998 23.1085 8.14558 23.78 6.72918 24.1763C5.31279 24.5725 3.83218 24.6857 2.37201 24.5094C4.92094 26.1486 7.88814 27.0189 10.9187 27.016C21.176 27.016 26.7853 18.5187 26.7853 11.1494C26.7853 10.9094 26.7787 10.6667 26.768 10.4294C27.8598 9.64025 28.8021 8.66272 29.5507 7.54269L29.5493 7.54136Z"
                                        fill="#D1D5DB"
                                    />
                                </svg>
                            </button>
                        </div>
                        <div className="flex justify-center items-center rounded-lg">
                            <button className="text-white text-2xl hover:text-gray-300 focus:outline-none focus:text-gray-300">
                                <svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M16 2.66663C8.63336 2.66663 2.66669 8.63329 2.66669 16C2.66518 18.799 3.54511 21.5274 5.18164 23.7982C6.81818 26.069 9.12822 27.7667 11.784 28.6506C12.4507 28.7666 12.7 28.3666 12.7 28.016C12.7 27.7 12.6827 26.6506 12.6827 25.5333C9.33335 26.1506 8.46669 24.7173 8.20002 23.9666C8.04936 23.5826 7.40002 22.4 6.83336 22.0826C6.36669 21.8333 5.70002 21.216 6.81602 21.2C7.86669 21.1826 8.61602 22.1666 8.86669 22.5666C10.0667 24.5826 11.984 24.016 12.7494 23.6666C12.8667 22.8 13.216 22.2173 13.6 21.884C10.6334 21.5506 7.53336 20.4 7.53336 15.3C7.53336 13.8493 8.04936 12.6506 8.90002 11.716C8.76669 11.3826 8.30002 10.016 9.03336 8.18263C9.03336 8.18263 10.1494 7.83329 12.7 9.55063C13.7854 9.24937 14.9069 9.09775 16.0334 9.09996C17.1667 9.09996 18.3 9.24929 19.3667 9.54929C21.916 7.81596 23.0334 8.18396 23.0334 8.18396C23.7667 10.0173 23.3 11.384 23.1667 11.7173C24.016 12.6506 24.5334 13.8333 24.5334 15.3C24.5334 20.4173 21.4174 21.5506 18.4507 21.884C18.9334 22.3 19.3507 23.1 19.3507 24.3506C19.3507 26.1333 19.3334 27.5666 19.3334 28.0173C19.3334 28.3666 19.584 28.7826 20.2507 28.6493C22.8974 27.7557 25.1972 26.0546 26.8266 23.7855C28.4559 21.5164 29.3326 18.7934 29.3334 16C29.3334 8.63329 23.3667 2.66663 16 2.66663Z"
                                        fill="#D1D5DB"
                                    />
                                </svg>
                            </button>
                        </div>
                        <div className="flex justify-center items-center rounded-lg">
                            <button className="text-white text-2xl hover:text-gray-300 focus:outline-none focus:text-gray-300">
                                <svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M24.4467 24.452H20.8933V18.8827C20.8933 17.5547 20.8667 15.8453 19.04 15.8453C17.188 15.8453 16.9053 17.2907 16.9053 18.7853V24.452H13.3507V13H16.764V14.56H16.8107C17.288 13.6613 18.448 12.7107 20.1813 12.7107C23.7813 12.7107 24.448 15.0813 24.448 18.1653V24.452H24.4467ZM9.33733 11.4333C9.06607 11.4337 8.79741 11.3805 8.54675 11.2768C8.29609 11.1731 8.06836 11.021 7.87661 10.8291C7.68486 10.6372 7.53287 10.4094 7.42935 10.1587C7.32582 9.90795 7.27281 9.63926 7.27333 9.368C7.2736 8.95978 7.39491 8.5608 7.62192 8.22153C7.84894 7.88225 8.17146 7.61791 8.54871 7.46194C8.92595 7.30596 9.34098 7.26536 9.74131 7.34525C10.1416 7.42515 10.5093 7.62197 10.7977 7.91081C11.0862 8.19965 11.2826 8.56755 11.3619 8.96798C11.4413 9.3684 11.4002 9.78338 11.2437 10.1604C11.0872 10.5375 10.8225 10.8597 10.4829 11.0862C10.1434 11.3128 9.74422 11.4336 9.336 11.4333H9.33733ZM11.1187 24.452H7.55467V13H11.12V24.452H11.1187ZM26.2267 4H5.772C4.79067 4 4 4.77333 4 5.72933V26.2707C4 27.2267 4.792 28 5.77067 28H26.2213C27.2 28 28 27.2267 28 26.2707V5.72933C28 4.77333 27.2 4 26.2213 4H26.2253H26.2267Z"
                                        fill="#D1D5DB"
                                    />
                                </svg>
                            </button>
                        </div>
                    </div>
                </div>
            </section>

            <div className="relative md:hidden mx-auto container w-full px-6 pb-20 pt-6  ">
                <div className="flex justify-between items-center">
                    <div className="flex justify-center items-center">
                        <button className="text-white" id="menu" aria-label="open menu" onClick={() => setSidebar(true)}>
                            <svg width="30" height="30" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M21 10H3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                <path d="M21 6H3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                <path d="M21 14H3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                <path d="M21 18H3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                            </svg>
                        </button>
                    </div>
                    <div className="flex justify-center items-center space-x-6">
                        <div className="flex justify-center items-center rounded-lg">
                            <button className="hover:text-gray-300 focus:outline-none focus:text-gray-300 text-white text-2xl">
                                <svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M29.5493 7.54136C28.5314 7.99162 27.452 8.28732 26.3467 8.41869C27.5117 7.72194 28.3836 6.62538 28.8 5.33336C27.7067 5.98402 26.508 6.44002 25.2587 6.68669C24.4195 5.7888 23.3072 5.19331 22.0946 4.9928C20.8821 4.7923 19.6373 4.99801 18.5537 5.57796C17.4701 6.15791 16.6085 7.0796 16.1028 8.19975C15.5971 9.31989 15.4757 10.5757 15.7573 11.772C13.5402 11.6609 11.3711 11.0847 9.39106 10.0809C7.411 9.0771 5.66418 7.66809 4.26401 5.94536C3.7684 6.79662 3.50795 7.76433 3.50934 8.74936C3.50934 10.6827 4.49334 12.3907 5.98934 13.3907C5.10402 13.3628 4.23819 13.1237 3.46401 12.6934V12.7627C3.46428 14.0503 3.90983 15.2982 4.72514 16.2948C5.54044 17.2914 6.67532 17.9753 7.93734 18.2307C7.1155 18.4534 6.25375 18.4862 5.41734 18.3267C5.77317 19.435 6.46668 20.4043 7.4008 21.0988C8.33491 21.7934 9.46285 22.1784 10.6267 22.2C9.46998 23.1085 8.14558 23.78 6.72918 24.1763C5.31279 24.5725 3.83218 24.6857 2.37201 24.5094C4.92094 26.1486 7.88814 27.0189 10.9187 27.016C21.176 27.016 26.7853 18.5187 26.7853 11.1494C26.7853 10.9094 26.7787 10.6667 26.768 10.4294C27.8598 9.64025 28.8021 8.66272 29.5507 7.54269L29.5493 7.54136Z"
                                        fill="#D1D5DB"
                                    />
                                </svg>
                            </button>
                        </div>
                        <div className="flex justify-center items-center rounded-lg">
                            <button className="hover:text-gray-300 focus:outline-none focus:text-gray-300 text-white text-2xl">
                                <svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M16 2.66663C8.63336 2.66663 2.66669 8.63329 2.66669 16C2.66518 18.799 3.54511 21.5274 5.18164 23.7982C6.81818 26.069 9.12822 27.7667 11.784 28.6506C12.4507 28.7666 12.7 28.3666 12.7 28.016C12.7 27.7 12.6827 26.6506 12.6827 25.5333C9.33335 26.1506 8.46669 24.7173 8.20002 23.9666C8.04936 23.5826 7.40002 22.4 6.83336 22.0826C6.36669 21.8333 5.70002 21.216 6.81602 21.2C7.86669 21.1826 8.61602 22.1666 8.86669 22.5666C10.0667 24.5826 11.984 24.016 12.7494 23.6666C12.8667 22.8 13.216 22.2173 13.6 21.884C10.6334 21.5506 7.53336 20.4 7.53336 15.3C7.53336 13.8493 8.04936 12.6506 8.90002 11.716C8.76669 11.3826 8.30002 10.016 9.03336 8.18263C9.03336 8.18263 10.1494 7.83329 12.7 9.55063C13.7854 9.24937 14.9069 9.09775 16.0334 9.09996C17.1667 9.09996 18.3 9.24929 19.3667 9.54929C21.916 7.81596 23.0334 8.18396 23.0334 8.18396C23.7667 10.0173 23.3 11.384 23.1667 11.7173C24.016 12.6506 24.5334 13.8333 24.5334 15.3C24.5334 20.4173 21.4174 21.5506 18.4507 21.884C18.9334 22.3 19.3507 23.1 19.3507 24.3506C19.3507 26.1333 19.3334 27.5666 19.3334 28.0173C19.3334 28.3666 19.584 28.7826 20.2507 28.6493C22.8974 27.7557 25.1972 26.0546 26.8266 23.7855C28.4559 21.5164 29.3326 18.7934 29.3334 16C29.3334 8.63329 23.3667 2.66663 16 2.66663Z"
                                        fill="#D1D5DB"
                                    />
                                </svg>
                            </button>
                        </div>
                        <div className="flex justify-center items-center rounded-lg">
                            <button className="hover:text-gray-300 focus:outline-none focus:text-gray-300 text-white text-2xl">
                                <svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M24.4467 24.452H20.8933V18.8827C20.8933 17.5547 20.8667 15.8453 19.04 15.8453C17.188 15.8453 16.9053 17.2907 16.9053 18.7853V24.452H13.3507V13H16.764V14.56H16.8107C17.288 13.6613 18.448 12.7107 20.1813 12.7107C23.7813 12.7107 24.448 15.0813 24.448 18.1653V24.452H24.4467ZM9.33733 11.4333C9.06607 11.4337 8.79741 11.3805 8.54675 11.2768C8.29609 11.1731 8.06836 11.021 7.87661 10.8291C7.68486 10.6372 7.53287 10.4094 7.42935 10.1587C7.32582 9.90795 7.27281 9.63926 7.27333 9.368C7.2736 8.95978 7.39491 8.5608 7.62192 8.22153C7.84894 7.88225 8.17146 7.61791 8.54871 7.46194C8.92595 7.30596 9.34098 7.26536 9.74131 7.34525C10.1416 7.42515 10.5093 7.62197 10.7977 7.91081C11.0862 8.19965 11.2826 8.56755 11.3619 8.96798C11.4413 9.3684 11.4002 9.78338 11.2437 10.1604C11.0872 10.5375 10.8225 10.8597 10.4829 11.0862C10.1434 11.3128 9.74422 11.4336 9.336 11.4333H9.33733ZM11.1187 24.452H7.55467V13H11.12V24.452H11.1187ZM26.2267 4H5.772C4.79067 4 4 4.77333 4 5.72933V26.2707C4 27.2267 4.792 28 5.77067 28H26.2213C27.2 28 28 27.2267 28 26.2707V5.72933C28 4.77333 27.2 4 26.2213 4H26.2253H26.2267Z"
                                        fill="#D1D5DB"
                                    />
                                </svg>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <div className={!sidebar ? "bg-white fixed top-0 w-full h-full transform -translate-x-full z-40 transition duration-700 md:hidden" : "bg-white fixed top-0 w-full h-full transform translate-x-0 z-40 transition duration-700 md:hidden"} id="mobile-nav">
                <div className=" opacity-50 w-full h-full" onClick={() => setSidebar(false)}></div>
                <div className="bg-gray-900 w-full  h-full shadow-lg  z-40 fixed overflow-y-auto z-40 top-0    flex-col justify-between xl:hidden pb-4 transition duration-500 ease-in-out">
                    <div className="px-6 h-full">
                        <div className="flex flex-col  justify-between h-full w-full">
                            <div>
                                <div className="border-b border-gray-300  flex justify-between items-center">
                                    <div className="w-10">
                                        <svg viewBox="0 0 63 63" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path
                                                d="M2 31.5L0 31.5L2 31.5ZM13.0625 31.5L11.0625 31.5L13.0625 31.5ZM31.5 49.9375L31.5 51.9375L31.5 49.9375ZM49.9375 31.5L51.9375 31.5L49.9375 31.5ZM31.5 0C23.1457 0 15.1335 3.31874 9.22614 9.22614L12.0546 12.0546C17.2118 6.89731 24.2065 4 31.5 4V0ZM9.22614 9.22614C3.31874 15.1335 0 23.1457 0 31.5L4 31.5C4 24.2065 6.89731 17.2118 12.0546 12.0546L9.22614 9.22614ZM0 31.5C0 39.8543 3.31874 47.8665 9.22614 53.7739L12.0546 50.9454C6.89731 45.7882 4 38.7935 4 31.5L0 31.5ZM9.22614 53.7739C15.1335 59.6813 23.1457 63 31.5 63V59C24.2065 59 17.2118 56.1027 12.0546 50.9454L9.22614 53.7739ZM31.5 63C39.8543 63 47.8665 59.6813 53.7739 53.7739L50.9454 50.9454C45.7882 56.1027 38.7935 59 31.5 59V63ZM53.7739 53.7739C59.6813 47.8665 63 39.8543 63 31.5H59C59 38.7935 56.1027 45.7882 50.9454 50.9454L53.7739 53.7739ZM63 31.5C63 23.1457 59.6813 15.1335 53.7739 9.22614L50.9454 12.0546C56.1027 17.2118 59 24.2065 59 31.5H63ZM53.7739 9.22614C47.8665 3.31874 39.8543 0 31.5 0V4C38.7935 4 45.7882 6.89731 50.9454 12.0546L53.7739 9.22614ZM31.5 11.0625C26.0796 11.0625 20.8813 13.2157 17.0485 17.0485L19.8769 19.8769C22.9596 16.7943 27.1405 15.0625 31.5 15.0625L31.5 11.0625ZM17.0485 17.0485C13.2157 20.8813 11.0625 26.0796 11.0625 31.5L15.0625 31.5C15.0625 27.1405 16.7943 22.9596 19.8769 19.8769L17.0485 17.0485ZM11.0625 31.5C11.0625 36.9204 13.2157 42.1187 17.0485 45.9515L19.8769 43.1231C16.7943 40.0404 15.0625 35.8595 15.0625 31.5L11.0625 31.5ZM17.0485 45.9515C20.8813 49.7843 26.0796 51.9375 31.5 51.9375L31.5 47.9375C27.1405 47.9375 22.9596 46.2057 19.8769 43.1231L17.0485 45.9515ZM31.5 51.9375C36.9204 51.9375 42.1187 49.7843 45.9515 45.9515L43.1231 43.1231C40.0404 46.2057 35.8595 47.9375 31.5 47.9375L31.5 51.9375ZM45.9515 45.9515C49.7843 42.1187 51.9375 36.9204 51.9375 31.5L47.9375 31.5C47.9375 35.8595 46.2057 40.0404 43.1231 43.1231L45.9515 45.9515ZM51.9375 31.5C51.9375 26.0796 49.7843 20.8813 45.9515 17.0485L43.1231 19.8769C46.2057 22.9596 47.9375 27.1405 47.9375 31.5L51.9375 31.5ZM45.9515 17.0485C42.1187 13.2157 36.9204 11.0625 31.5 11.0625L31.5 15.0625C35.8595 15.0625 40.0404 16.7943 43.1231 19.8769L45.9515 17.0485ZM19.1881 15.1883C12.691 20.3859 8.9769 26.6947 8.30509 34.0846C7.63993 41.4012 9.98264 49.5007 15.0135 58.3048L18.4865 56.3202C13.684 47.9159 11.7246 40.6508 12.2887 34.4467C12.846 28.3157 15.8923 22.9474 21.6869 18.3117L19.1881 15.1883ZM43.8119 47.8117C50.3006 42.6208 54.0216 36.3813 54.6947 29.0496C55.3609 21.7936 53.0141 13.7583 47.9865 4.95989L44.5135 6.94444C49.3192 15.3544 51.2745 22.5513 50.7115 28.6839C50.1554 34.7407 47.1161 40.0459 41.3131 44.6883L43.8119 47.8117Z"
                                                fill="white"
                                            />
                                        </svg>
                                    </div>
                                    <div className="mt-6 flex w-full items-end justify-end">
                                        <div className=" pb-8 flex items-center justify-end w-full">
                                            <button id="cross" aria-label="close menu" className="focus:outline-none focus:ring-2 rounded-md text-white" onClick={() => setSidebar(false)}>
                                                <svg xmlns="http://www.w3.org/2000/svg" className="icon icon-tabler icon-tabler-x" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                    <path stroke="none" d="M0 0h24v24H0z"></path>
                                                    <line x1="18" y1="6" x2="6" y2="18"></line>
                                                    <line x1="6" y1="6" x2="18" y2="18"></line>
                                                </svg>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                <ul className="">
                                    <li>
                                        <a className="cursor-pointer">
                                            <div className="text-gray-800 pt-10">
                                                <div className="flex items-center  hover:text-gray-300 text-base text-white">
                                                    <a onClick={() => router.push("/landingPage")} className="focus:outline-none cursor-pointer">
                                                        Intro
                                                    </a>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <a className="cursor-pointer">
                                            <div className="text-gray-800 pt-8">
                                                <div className="flex items-center">
                                                    <div className="flex items-center hover:text-gray-300 text-base text-white">
                                                        <a href="javascript:void(0)" className="focus:outline-none  cursor-pointer ">
                                                            Clients
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <a className="cursor-pointer">
                                            <div className="text-gray-800 pt-8">
                                                <div className="flex items-center  hover:text-gray-300 text-base text-white">
                                                    <a onClick={() => router.push("/work")} className="focus:outline-none cursor-pointer ">
                                                        Work
                                                    </a>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li className="text-gray-800 pt-8 cursor-pointer">
                                        <div className="flex items-center ">
                                            <div className="flex items-center  hover:text-gray-300 text-base text-white">
                                                <div className="w-6 h-6 md:w-8 md:h-8 ">
                                                    <a href="#contact" className="focus:outline-none cursor-pointer ">
                                                        Contact
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <section className="mt-14">
                <div className="mx-auto container  px-6 lg:px-14 xl:px-0">
                    <div className="flex flex-col justify-center items-start">
                        <div className="flex justify-start items-start">
                            <h1 className="xl:text-6xl md:text-5xl text-4xl font-extrabold  text-white">Highlights</h1>
                        </div>
                        <div className="flex justify-start items-start flex-col md:flex-row md:space-x-8 mt-8	">
                            <div className="px-8 py-10 mt-4 bg-gray-800 flex  justify-start items-start flex-col rounded">
                                <div className="">
                                    <p className="text-xs font-medium leading-3 text-white">JAVASCRIPT</p>
                                </div>
                                <div className="md:mt-2">
                                    <p className="text-2xl md:text-3xl font-semibold lg:leading-7 text-white">Front-end architecture</p>
                                </div>
                                <div className="mt-2 md:mt-4 ">
                                    <p className="text-base leading-normal text-gray-300 ">It is a long established fact that a reader will be distracted by the readable content for remote Junior Web Developer for Coolor, located in Las Vegas</p>
                                </div>
                                <div className="mt-3 md:mt-6">
                                    <div className="inline-flex space-x-2 items-center justify-start w-40 h-4">
                                        <svg width="14" height="2" viewBox="0 0 14 2" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <rect width="14" height="2" fill="#9CA3AF" />
                                        </svg>

                                        <p className="text-base leading-none text-gray-400">Schinner Systems</p>
                                    </div>
                                </div>
                            </div>
                            <div className="px-8 py-10 mt-4 bg-gray-800 flex  justify-start items-start flex-col rounded">
                                <div className="">
                                    <p className="text-xs font-medium leading-3 text-white">JAVASCRIPT</p>
                                </div>
                                <div className="md:mt-2">
                                    <p className="text-2xl md:text-3xl font-semibold lg:leading-7  text-white">Building an MVP in react</p>
                                </div>
                                <div className="mt-2 md:mt-4 ">
                                    <p className="text-base leading-normal text-gray-300 ">It is a long established fact that a reader will be distracted by the readable content for remote Junior Web Developer for Coolor, located in Las Vegas</p>
                                </div>
                                <div className="mt-3 md:mt-6">
                                    <div className="inline-flex space-x-2 items-center justify-start w-40 h-4">
                                        <svg width="14" height="2" viewBox="0 0 14 2" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <rect width="14" height="2" fill="#9CA3AF" />
                                        </svg>

                                        <p className="text-base leading-none text-gray-400"> Casper LLC</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section className="mt-24">
                <div className="mx-auto container px-6 lg:px-14 xl:px-0">
                    <div className="flex justify-center items-start flex-col space-y-8">
                        <div className="flex justify-start items-start">
                            <h1 className="xl:text-6xl md:text-5xl text-4xl font-extrabold text-right text-white">Work</h1>
                        </div>
                        <div className="w-full items-center grid xl:grid-cols-4 md:grid-cols-3 grid-cols-2 xl:gap-x-6 xl:gap-y-6 gap-x-4 md:gap-x-6 mt-16 xl:mt-0 gap-y-4 md:gap-y-6">
                            <div className=" flex flex-col justify-between items-start p-3 md:p-6 bg-gray-800 rounded">
                                <div className="w-full">
                                    <div className="flex justify-center items-center w-full">
                                        <img className="w-full" src={"https://cdn.tuk.dev/assets/templates/portfolio/rectangle.png"} alt="spider-web" />
                                    </div>
                                    <div className="md:mt-6 mt-4">
                                        <p className="text-xs font-medium leading-3 text-white">JAVASCRIPT</p>
                                    </div>
                                    <div className="md:mt-4 mt-2">
                                        <p className=" text-base md:text-2xl font-semibold lg:leading-8 text-white">Building an Interactive Showcase with Vue.js & Vue Instant Search </p>
                                    </div>
                                </div>
                                <div className="mt-4">
                                    <a onClick={() => router.push("/projectInner")} className="cursor-pointer focus:outline-none focus:underline text-xs  hover:underline focus:underline text-gray-300">
                                        <p>Go to project</p>
                                    </a>
                                </div>
                            </div>
                            <div className=" flex flex-col justify-between items-start h-full p-3 md:p-6 bg-gray-800 rounded">
                                <div className="w-full">
                                    <div className="w-full flex justify-center items-center">
                                        <img className="w-full" src={"https://cdn.tuk.dev/assets/templates/portfolio/book.png"} alt="book" />
                                    </div>
                                    <div className="md:mt-6 mt-4">
                                        <p className="text-xs font-medium leading-3 text-white">JAVASCRIPT</p>
                                    </div>
                                    <div className="md:mt-4 mt-2">
                                        <p className=" text-base md:text-2xl font-semibold lg:leading-8 text-white">In Defense of Utility-First CSS</p>
                                    </div>
                                </div>
                                <div className="mt-4">
                                    <a onClick={() => router.push("/projectInner")} className="cursor-pointer focus:outline-none focus:underline text-xs  hover:underline focus:underline text-gray-300">
                                        <p>Go to project</p>
                                    </a>
                                </div>
                            </div>
                            <div className=" flex flex-col h-full justify-between items-start p-3 md:p-6 bg-gray-800 rounded">
                                <div className="w-full">
                                    <div className="w-full justify-end items-center">
                                        <img className="w-full" src={"https://cdn.tuk.dev/assets/templates/portfolio/coding.png"} alt="book" />
                                    </div>
                                    <div className="md:mt-6 mt-4">
                                        <p className="text-xs font-medium leading-3 text-white">JAVASCRIPT</p>
                                    </div>
                                    <div className="md:mt-4 mt-2">
                                        <p className=" text-base md:text-2xl font-semibold lg:leading-8 text-white">Why Javascript Numbers Are Weird (And How to Fix It)</p>
                                    </div>
                                </div>
                                <div className="mt-4">
                                    <a onClick={() => router.push("/projectInner")}  className="cursor-pointer focus:outline-none focus:underline text-xs  hover:underline focus:underline text-gray-300">
                                        <p>Go to project</p>
                                    </a>
                                </div>
                            </div>
                            <div className=" flex flex-col h-full justify-between items-start p-3 md:p-6 bg-gray-800 rounded">
                                <div className="w-full">
                                    <div className="w-full items-center justify-center">
                                        <img className="w-full" src={"https://cdn.tuk.dev/assets/templates/portfolio/chrome.png"} alt="book" />
                                    </div>
                                    <div className="md:mt-6 mt-4">
                                        <p className="text-xs font-medium leading-3 text-white">JAVASCRIPT</p>
                                    </div>
                                    <div className="md:mt-4 mt-2">
                                        <p className="xl:w-60 text-base md:text-2xl font-semibold lg:leading-8 text-white">Scalable Responsive Systems</p>
                                    </div>
                                </div>
                                <div className="mt-4">
                                    <a onClick={() => router.push("/projectInner")}  className="cursor-pointer focus:outline-none focus:underline text-xs  hover:underline focus:underline text-gray-300">
                                        <p>Go to project</p>
                                    </a>
                                </div>
                            </div>
                            <div className=" flex flex-col justify-between items-start p-3 md:p-6 bg-gray-800 rounded">
                                <div className="w-full">
                                    <div className="flex justify-center items-center w-full">
                                        <img className="w-full" src={"https://cdn.tuk.dev/assets/templates/portfolio/rectangle.png"} alt="spider-web" />
                                    </div>
                                    <div className="md:mt-6 mt-4">
                                        <p className="text-xs font-medium leading-3 text-white">JAVASCRIPT</p>
                                    </div>
                                    <div className="md:mt-4 mt-2">
                                        <p className=" text-base md:text-2xl font-semibold lg:leading-8 text-white">Building an Interactive Showcase with Vue.js & Vue Instant Search </p>
                                    </div>
                                </div>
                                <div className="mt-4">
                                    <a onClick={() => router.push("/projectInner")}  className="cursor-pointer focus:outline-none focus:underline text-xs  hover:underline focus:underline text-gray-300">
                                        <p>Go to project</p>
                                    </a>
                                </div>
                            </div>
                            <div className=" flex flex-col justify-between items-start h-full p-3 md:p-6 bg-gray-800 rounded">
                                <div className="w-full">
                                    <div className="w-full flex justify-center items-center">
                                        <img className="w-full" src={"https://cdn.tuk.dev/assets/templates/portfolio/book.png"} alt="book" />
                                    </div>
                                    <div className="md:mt-6 mt-4">
                                        <p className="text-xs font-medium leading-3 text-white">JAVASCRIPT</p>
                                    </div>
                                    <div className="md:mt-4 mt-2">
                                        <p className=" text-base md:text-2xl font-semibold lg:leading-8 text-white">In Defense of Utility-First CSS</p>
                                    </div>
                                </div>
                                <div className="mt-4">
                                    <a onClick={() => router.push("/projectInner")}  className="cursor-pointer focus:outline-none focus:underline text-xs  hover:underline focus:underline text-gray-300">
                                        <p>Go to project</p>
                                    </a>
                                </div>
                            </div>
                            <div className=" flex flex-col h-full justify-between items-start p-3 md:p-6 bg-gray-800 rounded">
                                <div className="w-full">
                                    <div className="w-full justify-end items-center">
                                        <img className="w-full" src={"https://cdn.tuk.dev/assets/templates/portfolio/coding.png"} alt="book" />
                                    </div>
                                    <div className="md:mt-6 mt-4">
                                        <p className="text-xs font-medium leading-3 text-white">JAVASCRIPT</p>
                                    </div>
                                    <div className="md:mt-4 mt-2">
                                        <p className=" text-base md:text-2xl font-semibold lg:leading-8 text-white">Why Javascript Numbers Are Weird (And How to Fix It)</p>
                                    </div>
                                </div>
                                <div className="mt-4">
                                    <a onClick={() => router.push("/projectInner")}  className="cursor-pointer focus:outline-none focus:underline text-xs  hover:underline focus:underline text-gray-300">
                                        <p>Go to project</p>
                                    </a>
                                </div>
                            </div>
                            <div className=" flex flex-col h-full justify-between items-start p-3 md:p-6 bg-gray-800 rounded">
                                <div className="w-full">
                                    <div className="w-full items-center justify-center">
                                        <img className="w-full" src={"https://cdn.tuk.dev/assets/templates/portfolio/chrome.png"} alt="book" />
                                    </div>
                                    <div className="md:mt-6 mt-4">
                                        <p className="text-xs font-medium leading-3 text-white">JAVASCRIPT</p>
                                    </div>
                                    <div className="md:mt-4 mt-2">
                                        <p className="xl:w-60 text-base md:text-2xl font-semibold lg:leading-8 text-white">Scalable Responsive Systems</p>
                                    </div>
                                </div>
                                <div className="mt-4">
                                    <a onClick={() => router.push("/projectInner")}  className="cursor-pointer focus:outline-none focus:underline text-xs  hover:underline focus:underline text-gray-300">
                                        <p>Go to project</p>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section className="mt-24">
                <div className="container mx-auto px-6 lg:px-14 xl:px-0">
                    <div className="flex justify-start items-start flex-col space-y-14">
                        <div className="">
                            <h1 className="xl:text-6xl md:text-5xl text-4xl font-extrabold text-white">Technology stack</h1>
                        </div>
                        <div className="flex flex-col space-y-4  md:space-y-14">
                            <div>
                                <div className=" flex md:justify-start justify-between item-start flex-row space-x-3 xl:space-x-14 md:space-x-4 border-gray-700 border-b w-full h-full">
                                    <div>
                                        <button className=" font-medium lg:leading-6 focus:outline-none  pb-2 md:pb-4 xl:pb-2 text-xs md:text-xl xl:text-2xl pr-2 md:mr-0 border-b-2 xl:border-b-4 border-transparent focus:border-white text-gray-400 hover:text-white focus:text-white">
                                            <p>Back-end</p>
                                        </button>
                                    </div>
                                    <div>
                                        <button className=" font-medium lg:leading-6 focus:outline-none  pb-2 md:pb-4 xl:pb-2 text-xs md:text-xl xl:text-2xl  pr-2 md:mr-0 border-b-2 xl:border-b-4 border-transparent focus:border-white text-gray-400 hover:text-white focus:text-white">
                                            <p>Front-end</p>
                                        </button>
                                    </div>
                                    <div>
                                        <button className=" font-medium lg:leading-6 focus:outline-none text-left  pb-2 md:pb-4 xl:pb-2 text-xs md:text-xl xl:text-2xl  pr-2 md:mr-0 border-b-2 xl:border-b-4 border-transparent focus:border-white text-gray-400 hover:text-white focus:text-white">
                                            <p>Infrastructure & tools</p>
                                        </button>
                                    </div>
                                    <div>
                                        <button className=" font-medium lg:leading-6 focus:outline-none  pb-2 md:pb-4 xl:pb-2 text-xs md:text-xl xl:text-2xl  pr-2 md:mr-0 border-b-2 xl:border-b-4 border-transparent focus:border-white text-gray-400 hover:text-white focus:text-white">
                                            <p>Testing</p>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <div className="w-full flex justify-center items-center flex-col space-y-6">
                                <div className="w-full flex justify-center xl:items-center xl:flex-row flex-col xl:space-x-6 space-y-6 xl:space-y-0 ">
                                    <div className="flex xl:flex-row md:space-x-6 space-x-2 ml-2 md:ml-0">
                                        <div className="inline-flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">NodeJS</p>
                                        </div>
                                        <div className="inline-flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Python</p>
                                        </div>
                                        <div className="inline-flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">PHP</p>
                                        </div>

                                        <div className="inline-flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">GraphQL</p>
                                        </div>

                                        <div className="hidden sm:flex flex-shrink-0 items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-base leading-none text-white">Web Sockets</p>
                                        </div>

                                        <div className="hidden md:inline-flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-base leading-none text-white">Express</p>
                                        </div>
                                        <div className="hidden sm:flex xl:hidden items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Hapi</p>
                                        </div>

                                        <div className="hidden sm:flex md:hidden lg:flex xl:hidden items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">NestJS</p>
                                        </div>
                                    </div>
                                    <div className="flex flex-row md:space-x-6 space-x-2 ml-2 md:ml-0">
                                        <div className="flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Koa</p>
                                        </div>

                                        <div className="flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Hapi</p>
                                        </div>

                                        <div className="flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">NestJS</p>
                                        </div>

                                        <div className="flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className=" text-xs md:text-base leading-none text-white">Django</p>
                                        </div>

                                        <div className="hidden md:flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-base leading-none text-white">Laravel</p>
                                        </div>

                                        <div className="hidden sm:flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Wordpress</p>
                                        </div>
                                        <div className="hidden sm:flex xl:hidden items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Koa</p>
                                        </div>

                                        <div className="hidden sm:flex md:hidden lg:flex  xl:hidden items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Hapi</p>
                                        </div>

                                        <div className="hidden sm:flex md:hidden lg:flex xl:hidden items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">NestJS</p>
                                        </div>
                                    </div>
                                </div>
                                <div className="w-full flex justify-center xl:items-center xl:flex-row flex-col xl:space-x-6 space-y-6 xl:space-y-0 ">
                                    <div className="flex flex-row md:space-x-6 space-x-2">
                                        <div className="hidden md:inline-flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-base leading-none text-white">NodeJS</p>
                                        </div>
                                        <div className="hidden sm:inline-flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Python</p>
                                        </div>
                                        <div className="hidden sm:inline-flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">PHP</p>
                                        </div>

                                        <div className="inline-flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className=" text-xs md:text-base leading-none text-white">GraphQL</p>
                                        </div>

                                        <div className="flex flex-shrink-0 items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Web Sockets</p>
                                        </div>

                                        <div className="inline-flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Express</p>
                                        </div>
                                        <div className="hidden sm:flex xl:hidden items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Koa</p>
                                        </div>

                                        <div className="hidden sm:flex md:hidden lg:flex xl:hidden items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Hapi</p>
                                        </div>
                                    </div>
                                    <div className="flex flex-row md:space-x-6 space-x-2">
                                        <div className="hidden md:flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-base leading-none text-white">Koa</p>
                                        </div>

                                        <div className="hidden md:flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-base leading-none text-white">Hapi</p>
                                        </div>

                                        <div className="flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">NestJS</p>
                                        </div>

                                        <div className="hidden sm:flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-base leading-none text-white">Django</p>
                                        </div>

                                        <div className="flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Laravel</p>
                                        </div>

                                        <div className="flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Wordpress</p>
                                        </div>
                                        <div className="hidden sm:flex xl:hidden items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Koa</p>
                                        </div>

                                        <div className="hidden sm:flex md:hidden lg:flex xl:hidden items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Hapi</p>
                                        </div>

                                        <div className="hidden sm:flex md:hidden lg:flex xl:hidden items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">NestJS</p>
                                        </div>
                                    </div>
                                </div>
                                <div className="w-full flex justify-center xl:items-center xl:flex-row flex-col xl:space-x-6 space-y-6 xl:space-y-0 ">
                                    <div className="flex flex-row md:space-x-6 space-x-2 ml-2 md:ml-0">
                                        <div className="inline-flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">NodeJS</p>
                                        </div>
                                        <div className="inline-flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Python</p>
                                        </div>
                                        <div className="inline-flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">PHP</p>
                                        </div>

                                        <div className="hidden md:inline-flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-base leading-none text-white">GraphQL</p>
                                        </div>

                                        <div className="hidden sm:flex flex-shrink-0 items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-base leading-none text-white">Web Sockets</p>
                                        </div>

                                        <div className="hidden sm:inline-flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-base leading-none text-white">Express</p>
                                        </div>
                                        <div className="hidden sm:flex xl:hidden items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Koa</p>
                                        </div>

                                        <div className="hidden sm:flex md:hidden lg:flex xl:hidden items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">NestJS</p>
                                        </div>
                                    </div>
                                    <div className="flex flex-row md:space-x-6  space-x-2 ml-2 md:ml-0">
                                        <div className="flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Koa</p>
                                        </div>

                                        <div className="flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Hapi</p>
                                        </div>

                                        <div className="hidden md:flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-base leading-none text-white">NestJS</p>
                                        </div>

                                        <div className="hidden md:flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-base leading-none text-white">Django</p>
                                        </div>

                                        <div className="hidden sm:flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-base leading-none text-white">Laravel</p>
                                        </div>

                                        <div className="hidden sm:flex items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-base leading-none text-white">Wordpress</p>
                                        </div>
                                        <div className="hidden sm:flex xl:hidden items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Koa</p>
                                        </div>

                                        <div className="hidden sm:flex md:hidden lg:flex xl:hidden items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">Hapi</p>
                                        </div>

                                        <div className="hidden sm:flex md:hidden lg:flex xl:hidden items-center justify-start px-4 py-2 bg-gray-800 rounded">
                                            <p className="text-xs md:text-base leading-none text-white">NestJS</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section id="contact" className="mt-36">
                <div className="mx-auto container px-6 lg:px-14 xl:px-0">
                    <div className="flex xl:flex-row flex-col justify-between item-start">
                        <div className="flex justify-center item-start flex-col">
                            <div>
                                <p className="md:text-6xl text-4xl font-extrabold text-white">By the numbers</p>
                            </div>
                            <div className="grid grid-cols-2 md:mt-12 mt-6 gap-y-8">
                                <div className="flex flex-col justify-start items-start">
                                    <p className="text-xl md:text-3xl font-bold  text-white">1000+</p>
                                    <p className=" md:mt-4 text-lg md:text-2xl font-light leading-normal text-gray-300">Projects</p>
                                </div>
                                <div className="flex flex-col justify-start items-start">
                                    <p className="text-xl md:text-3xl font-bold  text-white">88%</p>
                                    <p className=" md:mt-4 text-lg md:text-2xl font-light leading-normal text-gray-300">Retention</p>
                                </div>
                                <div className="flex flex-col justify-start items-start">
                                    <p className="text-xl md:text-3xl font-bold  text-white">90%</p>
                                    <p className=" md:mt-4 text-lg md:text-2xl font-light leading-normal text-gray-300">Client retention</p>
                                </div>
                                <div className="flex flex-col justify-start items-start">
                                    <p className="text-xl md:text-3xl font-bold  text-white">90,000+</p>
                                    <p className=" md:mt-4 text-lg md:text-2xl font-light leading-normal text-gray-300">Users impacted</p>
                                </div>
                            </div>
                        </div>

                        <div className="mt-16 mb-10 sm:w-9/12  xl:mt-0 lg:w-4/5 xl:w-2/5 flex-col bg-gray-800 md:p-10 p-4 flex justify-center items-start space-y-9">
                            <div className="flex justify-center items-center w-full flex-col md:space-y-6 space-y-4">
                                <div className="w-full flex justify-start items-center">
                                    <input className="focus:ring-2  focus:ring-gray-300 focus:outline-none bg-gray-700  rounded w-full py-3 pl-2 text-base leading-none placeholder:text-gray-300 text-gray-300" type="text" placeholder="Your name" />
                                </div>
                                <div className="w-full flex justify-start items-center">
                                    <input className="focus:ring-2  focus:ring-gray-300 focus:outline-none bg-gray-700  rounded w-full py-3 pl-2 text-base leading-none placeholder:text-gray-300 text-gray-300" type="email" placeholder="Email address" />
                                </div>

                                <div className="w-full relative">
                                    <button onClick={dropdownHandler} className="focus:ring-2  focus:ring-gray-300 focus:outline-none w-full flex justify-between items-center bg-gray-700  rounded " data-menu>
                                        <p className="pl-2  py-3 text-gray-300 text-base ">{text}</p>
                                        <div className="cursor-pointer text-white mr-3">
                                            {dropDown ? (
                                                <svg id="svg2" xmlns="http://www.w3.org/2000/svg" className="icon icon-tabler icon-tabler-chevron-up" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                    <path stroke="none" d="M0 0h24v24H0z" />
                                                    <polyline points="6 15 12 9 18 15" />
                                                </svg>
                                            ) : (
                                                <svg id="svg1" xmlns="http://www.w3.org/2000/svg" className=" icon icon-tabler icon-tabler-chevron-up" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                    <path stroke="none" d="M0 0h24v24H0z" />
                                                    <polyline points="6 9 12 15 18 9" />
                                                </svg>
                                            )}
                                        </div>
                                    </button>
                                    {dropDown && (
                                        <ul onClick={() => setDropDown(false)} className="transition duration-300  ease-out bg-gray-700 dark:bg-gray-800 shadow rounded mt-2 py-1 w-full absolute">
                                            <li onClick={() => setText("China")}>
                                                {" "}
                                                <a tabindex="0" className=" focus:outline-none focus:text-gray-400  cursor-pointer text-white dark:text-gray-400 dark:hover:text-white hover:bg-indigo-700 hover:text-gray-400 ">
                                                    <div className=" px-3 py-3 text-base leading-3 tracking-normal   font-normal">China</div>
                                                </a>
                                            </li>
                                            <li onClick={() => setText("America")}>
                                                {" "}
                                                <a tabindex="0" className=" focus:outline-none focus:text-gray-400  cursor-pointer text-white dark:text-gray-400 dark:hover:text-white  hover:bg-indigo-700 hover:text-gray-400 ">
                                                    <div className="px-3 py-3 text-base leading-3 tracking-normal  font-normal">America</div>
                                                </a>
                                            </li>
                                            <li onClick={() => setText("France")}>
                                                {" "}
                                                <a tabindex="0" className=" focus:outline-none focus:text-gray-400  cursor-pointer text-white dark:text-gray-400 dark:hover:text-white hover:bg-indigo-700 hover:text-gray-400">
                                                    <div className=" text-base leading-3 tracking-normal py-3  px-3 font-normal">France</div>
                                                </a>
                                            </li>
                                        </ul>
                                    )}
                                </div>
                                <div className="w-full flex justify-start items-center">
                                    <textarea className="focus:ring-2 focus:ring-gray-300 focus:outline-none bg-gray-700 resize-none  rounded w-full py-3 px-2 text-base leading-none placeholder:text-gray-300 text-gray-300" placeholder="Project Description" cols="30" rows="5"></textarea>
                                </div>
                            </div>
                            <div className="w-full border rounded-sm border-white ">
                                <button className="focus:ring-2  focus:ring-gray-300 w-full focus:outline-none focus:text-gray-300  hover:text-gray-300 hover:bg-gray-900 text-base font-medium py-3 leading-none text-white">
                                    <p>Let’s get started on your project</p>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    );
};
export default Work;
